### ISSUE TITLE
Dev build issue - Arrays are not allowed in class constants

### ISSUE THREAD

**Issue by adrian-stein** [milkyway-multimedia/ss-shop-order-history#4]
Hey, I get an error when I do a dev build after installing the module with composer. I used the below composer line

> "milkyway-multimedia/ss-shop-order-history": "~0.3"

 And I get the following error:

`Fatal error: Arrays are not allowed in class constants in C:\Nimbler\ovesco\shop-order-history\code\OrderLog.php on line 157`

Any ideas on this? Looking on the net it talks about this being valid in newer version of PHP. I am running 5.4.22. Could this be why?

**Comment by mellm0** [comment]
Ah, sorry about that. Been testing in PHP5.6 and haven't had a chance to write tests. Please `composer update`and download new version (fixed @7939389f45d942a6daf87c7c1f6fc74c0e12d905)

**Comment by adrian-stein** [comment]
Yup that fixed it, thanks :)
